urls.py
from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from crosswords.views import *
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^crosswordaddict/', include('crosswordaddict.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='home'),
    url(r'^crossword/(?P<id>\d+)$', crossword, name="crossword"),
    url(r'^crossword2/(?P<id>\d+)$', crossword2, name="crossword2"),
    url(r'^puz/(?P<id>\d+)$', download_puz, name="download_puz"),
    (r'^save/$', crossword_save),
    (r'^add-note/$', crossword_add_note),
    (r'^add-favorite/$', clue_add_favorite),
    (r'^reveal/$', clue_reveal_answer),
    (r'^all/$', list_crosswords),
    url(r'^/(?P<newspaper>\w+)/(?P<name>\w+)$', crossword_detail,name="crossword_detail"), # Ex: thc-9936, gc-24766
    (r'^/(?P<newspaper>\w+)/$', crossword_category), # Ex: thc, ft, custom
    (r'^create/(?P<size>\d+)$', create),
)

# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:
    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

                                                                

crosswords/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models
from django.core.urlresolvers import reverse
from fields import CrosswordField

class CsClues(models.Model):
    crosswordid = models.IntegerField(null=True, db_column='crosswordId', blank=True) # Field name made lowercase.
    clue = models.CharField(max_length=300, blank=True)
    answer = models.CharField(max_length=90, blank=True) # user specific
    code = models.CharField(max_length=30, blank=True)
    square = models.IntegerField(null=True, blank=True)
    notes = models.TextField(blank=True) # user specific
    def __unicode__(self):
        return "%s"%(self.clue)
    class Meta:
        db_table = u'cs_clues'

class CsCrossword(models.Model):
    gridid = CrosswordField(db_column='gridId') # Field name made lowercase.
    complete = models.CharField(max_length=3, blank=True)
    dateadded = models.DateTimeField(db_column='dateAdded') # Field name made lowercase.
    user = models.CharField(max_length=90)
    def __unicode__(self):
        return "%d"%(self.id)
    class Meta:
        db_table = u'cs_crossword'

    def save(self, *args, **kwargs):
        super(CsCrossword, self).save(*args, **kwargs) # Call the "real" save() method.


class CsPresets(models.Model):
    grid = models.TextField()
    answers = models.TextField(blank=True)
    name = models.CharField(max_length=20, blank=True)
    description = models.TextField(blank=True)
    added = models.DateTimeField(auto_now_add=True)
    appeared = models.DateField(blank=True)

    def __unicode__(self):
        return "%s"%(self.grid)    

    def get_absolute_url(self):
        return reverse('crossword', args=(self.pk,))

    class Meta:
        db_table = u'cs_presets'

crosswords/forms.py
from django import forms
from django.forms.fields import DateField
from models import CsCrossword, CsPresets

class CrosswordInput(forms.TextInput):
    class Media:
        js = ('cwsJS.js')

    def render(self, name, value, attrs=None):
        output = super(CrosswordInput, self).render(name, value, attrs)
        return output + "<b> %s </b>" % (CsPresets.objects.get(id=value).grid)

class CrosswordForm(forms.Form):
    name = forms.CharField()
    description = forms.CharField()
    appeared = DateField()

crosswords/views.py
# Create your views here.
import math
from datetime import date
from .models import CsPresets, CsClues, CsCrossword
from django.shortcuts import render_to_response, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.core import serializers
from django.utils.datastructures import MultiValueDictKeyError
from django.utils import simplejson
from django.contrib.auth.models import User
from django.core.context_processors import csrf

from utils import get_clues, cw_obj
from forms import CrosswordForm
from favorites.models import Favorite
from puz import *

def index(request):
    return render_to_response('index.html')

def crossword(request, id):
    cspreset = get_object_or_404(CsPresets, pk=id)
    grid = cspreset.grid
    answers = cspreset.answers
    crossword_id = CsCrossword.objects.get(gridid=id).id
    cs_clues = CsClues.objects.filter(crosswordid=crossword_id)
    size = int(math.sqrt(len(grid)))
    u = User.objects.get(username='badri')
    number_info = dict([(int(x.square), {"code":x.code[:-1]}) for x in cs_clues])
    across = [({"square":int(x.square), "code":x.code[:-1], "clue":x.clue, "note":x.notes, "favorite": Favorite.objects.favorites_for_object(x,u).exists() }) for x in cs_clues if x.code[-1]=='A']
    down = [({"square":int(x.square), "code":x.code[:-1], "clue":x.clue, "note":x.notes, "favorite": Favorite.objects.favorites_for_object(x,u).exists()}) for x in cs_clues if x.code[-1]=='D']
    crossword = []
    for i,j in enumerate(grid):
        try:
            ans = answers[i]
        except IndexError:
            ans = ''
        if i+1 in number_info.keys():
            crossword.append({'grid':j, 'code': number_info[i+1]['code'], 'ans': ans})
        else:
            crossword.append({'grid':j, 'code': '', 'ans': ans})
    return render_to_response('crossword.html', {'crossword':crossword, 'across': across, 'down':down, 'grid_id': id, 'crossword_id': crossword_id, 'name': cspreset.name, 'appeared': cspreset.appeared, 'size': size, 'gridlen': len(grid)})

def download_puz(request, id):
    cspreset = get_object_or_404(CsPresets, pk=id)
    grid = cspreset.grid
    answers = cspreset.answers
    crossword_id = CsCrossword.objects.get(gridid=id).id
    cs_clues = CsClues.objects.filter(crosswordid=crossword_id)
    fill = {'0': '.', '1': '-'}
    answer_fill = {'0': '.', '1': 'A'}
    p = Puzzle()
    p.title = cspreset.name
    p.fill = ''.join([fill[x] for x in cspreset.grid])
    p.solution = ''.join([answer_fill[x] for x in cspreset.grid]) # hack
    p.width = 15
    p.height = 15
    p.clues = [x.clue for x in cs_clues]
    puz_file = '%s.puz' % cspreset.name.replace(" ", "-")
    response = HttpResponse(p.tostring(), content_type='application/x-puz')
    response['Content-Disposition'] = 'attachment; filename=%s' % puz_file
    return response


def crossword2(request, id):
    cspreset = get_object_or_404(CsPresets, pk=id)
    grid = cspreset.grid
    answers = cspreset.answers
    crossword_id = CsCrossword.objects.get(gridid=id).id
    cs_clues = CsClues.objects.filter(crosswordid=crossword_id)
    puzzle_data = simplejson.dumps([cw_obj(x) for x in cs_clues], indent=4)
    return render_to_response('crossword2.html', {'puzzle_data':puzzle_data, 'grid_id': id, 'crossword_id': crossword_id, 'name': cspreset.name, 'appeared': cspreset.appeared })

def list_crosswords(request):
    xwords = []
    xwords_data = CsPresets.objects.all()
    return render_to_response('crossword_list.html', {'xwords': xwords_data})

def crossword_save(request):
    if request.is_ajax():
        if 'grid_id' in request.POST:
            grid_id = request.POST['grid_id']
            grid = CsPresets.objects.get(id=grid_id)
            ans = []
            for i in range(1,226):
                try:
                    if not request.POST[str(i)]:
                        ans.append(' ')
                    else:
                        ans.append(request.POST[str(i)])
                except MultiValueDictKeyError:
                    ans.append(' ')

            grid.answers = ''.join(ans)
            grid.save()
            response = {'message' : 'Crossword saved successfully.'}
            data = simplejson.dumps(response)
            return HttpResponse(data, mimetype='application/json')
        else:
            response = {'message' : 'There was an error in saving the crossword.'}
            data = simplejson.dumps(response)
            return HttpResponse(data, mimetype='application/json')


    
def crossword_category(request):
    pass

def crossword_detail(request):
    pass

def create(request, size=15):
    if request.method == 'POST':
        xword = request.POST
        if xword['across'] and xword['down']:
            across_clues = get_clues(xword, 'A')
            down_clues = get_clues(xword, 'D')
            clues = across_clues + down_clues
        else:            
            clues = []
            for k,v in xword.iteritems():
                if '_A#' in k:
                    clue_num = k[:-3]
                    clue_text = xword[clue_num+'_A']
                    answer = xword[clue_num+'_AA']
                    answer_length = xword[clue_num+'_A_']
                    if not answer: answer = answer_length
                    grid_number = xword[clue_num+'_A_N']
                    clues.append({'clue':clue_text, 'answer':answer, 'square':grid_number, 'code':clue_num+'A'})
                if '_D#' in k:
                    clue_num = k[:-3]
                    clue_text = xword[clue_num+'_D']
                    answer = xword[clue_num+'_DA']
                    answer_length = xword[clue_num+'_D_']
                    if not answer: answer = answer_length
                    grid_number = xword[clue_num+'_D_N']
                    clues.append({'clue':clue_text, 'answer':answer, 'square':grid_number, 'code':clue_num+'D'})                
        # do some kind of error checking down here.
        grid = CsPresets(grid=xword['grid'], name=xword['name'], description=xword['description'], appeared=xword['appeared'])
        grid.save()
        crossword = CsCrossword(gridid=grid.id, dateadded=date.today(), user='bar')
        crossword.save()
        for c in clues:
            clue = CsClues(crosswordid=crossword.id, clue=c['clue'], answer=c['answer'], square=c['square'], code=c['code'])
            clue.save()
        response = simplejson.dumps({'success':'False', 'html':'<span> abc </span>'})
        return HttpResponse(response, mimetype="application/json")
    else:
        xwd_form = CrosswordForm()
        c = {'xword': xwd_form, 'size': size}
        c.update(csrf(request))
        return render_to_response('create.html', c)

def crossword_add_note(request):
    if request.is_ajax():
        resp = request.POST
        clue = CsClues.objects.get(crosswordid=resp['crossword'], code=resp['clue'])
        clue.notes = resp['note']
        clue.save()
        response = {'clue' : resp['clue'], 'note': resp['note']}
        data = simplejson.dumps(response)
        return HttpResponse(data, mimetype='application/json')

def clue_add_favorite(request):
    if request.is_ajax():
        resp = request.POST
        clue = CsClues.objects.get(crosswordid=resp['crossword'], code=resp['clue'])
        user = User.objects.get(username='badri')
        Favorite.objects.create_favorite(clue, user)
        response = {'clue' : resp['clue']}
        data = simplejson.dumps(response)
        return HttpResponse(data, mimetype='application/json')

def clue_reveal_answer(request):
    if request.is_ajax():
        resp = request.POST
        clue = CsClues.objects.get(crosswordid=resp['crossword'], code=resp['clue'])
        response = {'answer' : clue.answer}
        data = simplejson.dumps(response)
        return HttpResponse(data, mimetype='application/json')

crosswords/templates/create.html
<html>
  <head>
    <title>Create a new crossword</title>
    <link rel="stylesheet" href="/site_media/css/style.css" type="text/css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
    <script type="text/javascript" src="/site_media/js/cwsJS.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      drawCrossword( {{ size }}, {{ size }} );
      $(document).ready(function(){
      $("#id_appeared").datepicker({ dateFormat: 'yy-mm-dd' });
      $("#write_clues").click(function() {
      CW.removeNumbers(); CW.numberCrossword();
      writeclueAnswerBoxes();
      $("#paste_clues").hide();
      });
      $("#paste_clues").click(function() {
      CW.removeNumbers();
      CW.numberCrossword();
      writeAcrossDownBoxes();
      $("#write_clues").hide();
      });
      jQuery('a.minibutton').mousedown(function() {
      jQuery(this).addClass('mousedown');
      });
      jQuery('a.minibutton').blur(function() {
      jQuery(this).removeClass('mousedown');
      });
      jQuery('a.minibutton').mouseup(function() {
      jQuery(this).removeClass('mousedown');
      });
      $('#paperEntry').submit(function(e) {
      // must integrate with django forms, not needed for paste clues.
      // var validate = checkPaper();
      checkCrossword();
      e.preventDefault();
      var paper_entry = jQuery(e.target);
      jQuery.ajax({
      url: paper_entry.attr('action'),
      type: paper_entry.attr('method'),
      data: paper_entry.serialize(),
      dataType: 'json',
      success: function(json){
      alert(json);
      },
      error: function(xhr, ajaxOptions, thrownError){
      // log ajax errors?
      }
      });
      });
      });
    </script>
    <a href="#" class="minibutton"><span id="paste_clues">Paste Clues</span></a>
    <form id="paperEntry" action="/create/{{ size }}" method="POST" name="PaperEntry">{% csrf_token %}
      {{ xword.as_p }}
      <div id="CABoxes"></div>
    </form>
  </body>
</html>

crosswords/templates/crossword.html
<html>
  <head>
    <title>{{ name }} | xwords</title>
    <link href="http://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <script type="text/javascript" src="/site_media/js/jquery.hotkeys-0.7.8.js"></script>
    <link rel="stylesheet" href="/site_media/css/style.css" />
    <script type="text/javascript" charset="utf-8">
      function trim(s){ 
        return ( s || '' ).replace( /^\s+|\s+$/g, '' ); 
      }

      $(document).ready(function(){
      // defaults
      var align = "across";
      var in_focus = "0";
      var f = function(e) {
        $('#notes-form').show();
        $('#clue-id').attr('value', e.attr('data-code'));
        $('#clue-notes').val(trim(e.next().text()));
        $('#clue-text').text(e.text());
      };

      $('#write-note').click(function() {
      $.ajax({
        type: "POST",
        dataType: "json",
        url: "/add-note/",
        data: {
          "clue": $('#clue-id').val(),
          "note": $('#clue-notes').val(),
          "crossword" : {{ crossword_id }},
          csrfmiddlewaretoken: '{{ csrf_token }}' 
        },
        error: handleFail,
        success : write_node_success
      });
      });

      $('#add-favorite').click(function() {
        $.ajax({
          type: "POST",
          dataType: "json",
          url: "/add-favorite/",
          data: {
            "clue": $('#clue-id').val(),
            "crossword" : {{ crossword_id }},
            csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          error: handleFail,
          success : add_favorite_success
        });
      });

      $('#reveal').click(function() {
        $.ajax({
          type: "POST",
          dataType: "json",
          url: "/reveal/",
          data: { 
            "clue": $('#clue-id').val(),
            "crossword" : {{ crossword_id }},
            csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          error: handleFail,
          success : reveal_success
        });
      });
      
      $('#clue-notes').focus(function() {in_focus = "x";});
      var handleFail = function(xhr, msg) {alert(msg);}
      var write_node_success = function(data) {
        $("div").find("[data-code='" + data.clue + "']").next().text(data.note); 
      }
      var add_favorite_success = function(data) {
        $("div").find("[data-code='" + data.clue + "']").addClass('favorite'); 
      }

      var reveal_success = function(data) {
        $("#box_"+in_focus).css("background-color", "white");
        var next_square = in_focus;
        for(var i = 0;i< data.answer.length; ++i) {
          $("#box_"+next_square + "> .letter").text(data.answer[i]);
          $("#box_"+ next_square + "> input").val(data.answer[i]);
          in_focus = next_square;
          next_square = find_next_square();
        }
      }

      $(".across_clues > .clue").click(function(e) {
        align = "across";
        $("#box_"+in_focus).css("background-color", "white");
        in_focus = this.id.slice(0, this.id.length-1);
        $("#box_"+in_focus).css("background-color", "#99cc00");
        f($(this));
        if($(this).hasClass('favorite')) {
          $('#add-favorite').hide();
        }
        else {
          $('#add-favorite').show();
        }
      });

      $(".down_clues > .clue").click(function(e) {
        align = "down";
        $("#box_"+in_focus).css("background-color", "white");
        in_focus = this.id.slice(0, this.id.length-1);
        $("#box_"+in_focus).css("background-color", "#99cc00");
        f($(this));
        if($(this).hasClass('favorite')) {
          $('#add-favorite').hide();
        }
        else {
          $('#add-favorite').show();
        }
      });

      function find_next_square() {
        if(align == "across") {
          var next_square = parseInt(in_focus) + 1;
        }
        else {
          var next_square = parseInt(in_focus) + {{ size }};
        }
        return next_square;
      }

      function find_prev_square() {
        if(align == "across") {
          var prev_square = parseInt(in_focus) - 1;
        }
        else {
          var prev_square = parseInt(in_focus) - {{ size }};
        }
        return prev_square;
      }

      function is_across(current_box) {
        if((current_box % 15 == 0) || (current_box % 15 == 1)) {
          current_box= parseInt(current_box)+15;
          return ($("#box_"+current_box).attr("class").indexOf("black-box") != -1);
        }
        var next_square = parseInt(current_box) + 1;
        var prev_square = parseInt(current_box) - 1;
        if(next_square > {{ gridlen }}) {
          return true;
        }
        return ( ($("#box_"+next_square).attr("class").indexOf("black-box") == -1) || 
        ($("#box_"+prev_square).attr("class").indexOf("black-box") == -1) );
      }

      $(".tile").click(function(e) {
        var current_box = this.id.split("_")[1];
        if(is_across(current_box)) {
          align = "across";
        }
        else {
          align = "down";
        }
        $("#box_"+in_focus).css("background-color", "white");
        in_focus = this.id.split("_")[1];
        $("#box_"+in_focus).css("background-color", "#99cc00");
      });

      var bkspc = function(s){
        $("#box_"+in_focus).css("background-color", "white");
        in_focus = find_prev_square(); 
        $("#box_"+in_focus + "> .letter").text("");
        $("#box_"+in_focus + "> input").val("");
        $("#box_"+in_focus).css("background-color", "#99cc00");
      }

      $(document).bind('keydown', 'backspace', bkspc);


      var key_map = function(s) {
        $("#box_"+in_focus + "> .letter").text(String.fromCharCode(s.keyCode));
        $("#box_"+in_focus + "> input").val(String.fromCharCode(s.keyCode));
        $("#box_"+in_focus).css("background-color", "white");
        var next_square = find_next_square();
        if(next_square > {{ gridlen }}) { return false; }
        if($("#box_"+next_square).attr("class").indexOf("black-box") != -1) { return false; }
        in_focus = next_square;
        $("#box_"+in_focus).css("background-color", "#99cc00");
      }

    $('#grid-form').submit(function() {
      $.ajax({
        data: $(this).serialize(),
        dataType: "json",
        type: $(this).attr('method'),
        url: $(this).attr('action'),
        success: function(response) {
          $('div.save-message').html(response['message']);
        }
      });
      return false;
    });

    var alphabets = 'abcdefghijklmnopqrstuvwxyz';
    for(var i=0; i <= alphabets.length; i++) {
      $(document).bind('keydown', alphabets[i], key_map);
    }
  });
  </script> 
  </head>
  <body>
    <div id="page">
      <div id="heading">
	<h1>{{ name }}, {{ appeared|date:"jS F Y" }}</h1>	
      </div>
      <div class="save-message"></div>
      <form id="grid-form" action="/save/" method="POST">
	<input type="hidden" id="grid_id" name="grid_id" value="{{ grid_id }}"/>
	<div id="crossword">
	  <table class="grid">
	    <tr>
	      {% for i in crossword %}
	      {% if forloop.counter0|divisibleby:size %}
	    </tr>
	    <tr>
	      {% endif %}
	      {% ifequal i.grid "0" %}
	      <td>
		<div id="box_{{ forloop.counter }}" class="black-box"/>
		<input type="hidden" id="{{ forloop.counter }}" name="{{ forloop.counter }}" size="1" maxlength="1" disabled="disabled" class="black-box"/>
	      </td>
	      {% else %}
	      {% if i.code %}
	      <td>
		<div id="box_{{ forloop.counter }}" class="tile">
		  <div align="left" class="number">{{ i.code }}</div>
		  <div class="letter">{{ i.ans }}</div>
		  <input type="hidden" id="{{ forloop.counter }}" name="{{ forloop.counter }}" size="1" maxlength="1"  class="tile" value="{{ i.ans }}"/>
		</div>
	      </td>
	      {% else %}
	      <td>
		<div id="box_{{ forloop.counter }}" class="tile">
		  <div align="left" style="width:30px; height:15px;"></div>
		  <div class="letter">{{ i.ans }}</div>
		  <input type="hidden" id="{{ forloop.counter }}" name="{{ forloop.counter }}" size="1" maxlength="1" class="tile" value="{{ i.ans }}"/>
		</div>
	      </td>
	      {% endif %}
	      {% endifequal %}
	      {% endfor %}
	    </tr>
	  </table>
	</div>
	<div id="ops">
	  <div id="clue-text"></div>
	  <input type="submit" value="save crossword" id="save_crossword"/>
          <a href="{% url download_puz grid_id %}">Download .puz file</a>
	  <div id="notes-form">
            <input type="hidden" id="clue-id" name="clue-id" value=""/>
            <div><textarea rows="4" id="clue-notes"></textarea></div>
            <input type="submit" value="write note" id="write-note"/>
	    <input type="button" value="mark as favorite" id="add-favorite"/>
	    <input type="button" value="reveal" id="reveal"/>
	  </div>
	</div>
      </form>

      <div class="across_clues">
	<h3 class="title">Across</h3>
	{% for across_clue in across %}
	<div id="{{ across_clue.square }}c" class="clue {% if across_clue.favorite %} favorite {% endif %}" data-code="{{ across_clue.code }}A"> {{ across_clue.code }} {{ across_clue.clue }}</div>
	<div class="notes"> {{ across_clue.note }} </div>
	{% endfor %}
      </div>
      <div class="down_clues">
	<h3 class="title">Down</h3>
	{% for down_clue in down %}
	<div id="{{ down_clue.square }}c" class="clue{% if down_clue.favorite %} favorite {% endif %}" data-code="{{ down_clue.code }}D"> {{ down_clue.code }} {{ down_clue.clue }}</div>
	<div class="notes"> {{ down_clue.note }} </div>
	{% endfor %}
      </div>
    </div>
  </body>
</html>

crosswords/templates/crossword2.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>{{ name }} | xwords</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script src="/site_media/js/jquery.crossword.js"></script>
        <link rel="stylesheet" href="/site_media/css/c2.css" />
        <script>
	$( document ).ready(function() {

var puzzleData = {{puzzle_data|safe}};

	  $('#puzzle-wrapper').crossword(puzzleData);
        });
        </script>
</head>

<body>
<h1>{{ name }}, {{ appeared|date:"jS F Y" }}</h1>	
<div id="puzzle-wrapper"><!-- crossword puzzle appended here --></div>
</body>
</html>	

crosswords/templates/crossword_list.html
<html>
  <head>
    <style type="text/css">
      .white {color:black; margin:-3px;width:30px; height:30px; font:arial; font-weight:bold; font-size:20px; text-align:center;}
    </style>
  </head>
  <body>
    {% for i in xwords %}
    <p> 
      <a href="{{ i.get_absolute_url }}">{{ i.name }}</a>
      <i> {{ i.description }} </i>
    </p>
    {% endfor %}
  </body>
</html>

crosswords/templates/index.html
<html>
  <head>
    <style type="text/css">
      .white {color:black; margin:-3px;width:30px; height:30px; font:arial; font-weight:bold; font-size:20px; text-align:center;}
    </style>
  </head>
  <body>
    <form action="." method="GET">
      <input type="text" name="grid_id"/>
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>